services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: bot_music_discord_lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
      - ./lavalink/plugins:/opt/Lavalink/plugins
      - ./lavalink/logs:/opt/Lavalink/logs
